# Generated by Django 4.0.3 on 2022-05-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_remove_places_properties'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['object_id'], 'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.AlterField(
            model_name='image',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Позиция'),
        ),
    ]
