# Generated by Django 4.0.3 on 2022-05-03 01:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_image_options_alter_image_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='description_long',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
    ]
