# Generated by Django 4.0.3 on 2022-05-17 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_rename_places_place_rename_places_image_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='places.place', verbose_name='Места'),
        ),
    ]
